<?php

return [
    'adminEmail' => 'keigonec@126.com',
    'XiiError' => ['codes' => ['0403' => '验证失败非法请求.', '0408' => '验证码已过期.'],
                    'errorIgnore' => false,
                    'errorFormat' => 'json',
                    ],
    'XiiToken' => ['encryptMethod' => 'sha256', 
                    'privateKey' => '888888', 
                    'tokenIndex'=> 'API_TOKEN', 
                    'whereStart' => 5, 
                    'timeLimit' => 10],
    'XiiUploader' => ['pathFolder' => 'upload', 
                        'pathUseDateFormat' => true,
                        'sizeLimit' => true,
                        'sizeMin' => '5k',
                        'sizeMax' => '300k', 
                        'fileTypeLimit' => true,
                        'fileTypeAllow' => ['png', 'jpg', 'jpeg', 'gif'],
                        'fileNameEncrypt' => true, 
                        'thumbnailNeed' => true,
                        'thumbnailNeedOff' => 'Thumbnail is Off!',
                        'thumbnailSameType' => true,
                        'thumbnailPercent' => 5, 
                        'thumbnailWidth' => 0,
                        'thumbnailHeight' => 0, 
                        'thumbnailSuffix' => '_params_thumb',],
    'XiiArPlus' => ['_deleteField' => 'status',
                     '_deleteValue' => 9,
                     '_deleteForce' => true,
                     '_autoFill' => true,
                     '_autoFieldsPassword' => ['password'],
                     '_autoFieldsDateTime' => ['createDt'],
                     '_autoFieldsIp' => ['ip'],
                     '_autoMethodPassword' => 'sha256',
                     '_autoParamsPassword' => '',
                     '_autoParamsDateTime' => '',
                     ],
    'XiiPassword' => ['algo' => PASSWORD_DEFAULT,
                        'salt' => '',
                        'cost' => 11],
    'XiiCurl' => ['AllowEmptyData' => false],
];