<?php

return [
    'adminEmail' => 'keigonec@126.com',
    'XiiError' => ['_codes' => [403 => '验证失败非法请求.', 408 => '验证码已过期.', 409 => 'Model未设置.'],
                    '_errorIgnore' => false,
                    '_errorFormat' => 'json',
                    ],
    'XiiToken' => ['_encryptMethod' => 'sha256', 
                    '_privateKey' => '888888', 
                    '_tokenIndex'=> 'XII_API_TOKEN', 
                    '_whereStart' => 5, 
                    '_timeLimit' => 10],
    'XiiUploader' => ['_pathFolder' => 'upload', 
                        '_pathUseDateFormat' => true,
                        '_sizeLimit' => true,
                        '_sizeMin' => '5k',
                        '_sizeMax' => '300k', 
                        '_fileTypeLimit' => true,
                        '_fileTypeAllow' => ['png', 'jpg', 'jpeg', 'gif'],
                        '_fileNameEncrypt' => true, 
                        '_thumbnailNeed' => true,
                        '_thumbnailNeedOff' => 'Thumbnail is Off!',
                        '_thumbnailSameType' => true,
                        '_thumbnailPercent' => 5, 
                        '_thumbnailWidth' => 0,
                        '_thumbnailHeight' => 0, 
                        '_thumbnailSuffix' => '_params_thumb',],
    'XiiArPlus' => ['_deleteField' => 'status',
                     '_deleteValue' => 9,
                     '_deleteForce' => true,
                     '_autoFill' => true,
                     '_autoFieldsPassword' => ['password'],
                     '_autoFieldsDateTime' => ['createDt'],
                     '_autoFieldsIp' => ['ip'],
                     '_autoMethodPassword' => 'sha256',
                     '_autoParamsPassword' => '',
                     '_autoParamsDateTime' => '',
                     '_pageLinkPagerOn' => false,
                     ],
    'XiiPassword' => ['_algo' => PASSWORD_DEFAULT,
                        '_salt' => '',
                        '_cost' => 11],
    'XiiCurl' => ['_allowEmptyData' => true],
];